# Generated by Django 3.2.19 on 2023-08-04 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funix', '0002_auto_20230802_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('de', 'German'), ('el', 'Greek'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('pt', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sr-latn', 'Serbian (Latin)'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=7, verbose_name='language')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='translated name')),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='funix.coursecategory', verbose_name='course category')),
            ],
            options={
                'verbose_name': 'course category translation',
                'verbose_name_plural': 'course category translations',
                'unique_together': {('course_category', 'language')},
            },
        ),
        migrations.CreateModel(
            name='CourseSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('de', 'German'), ('el', 'Greek'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('pt', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sr-latn', 'Serbian (Latin)'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=7, verbose_name='language')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='translated name')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='funix.coursesection', verbose_name='course section')),
            ],
            options={
                'verbose_name': 'course section translation',
                'verbose_name_plural': 'course section translations',
                'unique_together': {('course_section', 'language')},
            },
        ),
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('de', 'German'), ('el', 'Greek'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('pt', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sr-latn', 'Serbian (Latin)'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=7, verbose_name='language')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='translated name')),
                ('description', models.TextField(verbose_name='translated description')),
                ('goals', models.TextField(verbose_name='translated goals')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='funix.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course translation',
                'verbose_name_plural': 'course translations',
                'unique_together': {('course', 'language')},
            },
        ),
        migrations.DeleteModel(
            name='CourseComment',
        ),
    ]
