# Generated by Django 3.2.19 on 2023-08-22 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funix', '0003_auto_20230804_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTestCaseDataTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('de', 'German'), ('el', 'Greek'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('pt', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sr-latn', 'Serbian (Latin)'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=7, verbose_name='language')),
                ('input_data', models.TextField(blank=True, verbose_name='input')),
                ('output_data', models.TextField(blank=True, verbose_name='expected output')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='funix.problemtestcasedata')),
            ],
            options={
                'verbose_name': 'testcase translation',
                'verbose_name_plural': 'testcase translations',
                'unique_together': {('testcase', 'language')},
            },
        ),
    ]
