# Generated by Django 3.2.19 on 2023-07-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0147_auto_20230612_0623'),
        ('funix', '0005_auto_20230710_1648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='probleminitialsource',
            unique_together={('problem', 'language')},
        ),
        migrations.CreateModel(
            name='SubmissionWPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.IntegerField(default=-1, null=True, verbose_name='Words Per Minutes')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wpm', to='judge.submission')),
            ],
        ),
    ]
