# Generated by Django 3.2.19 on 2023-07-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funix', '0008_auto_20230728_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseproblem',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate',
            field=models.CharField(blank=True, default='', max_length=225, verbose_name='Course Certificate'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Section Name'),
        ),
    ]
