# Generated by Django 3.2.19 on 2023-07-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funix', '0009_auto_20230729_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseproblem',
            options={'permissions': [('view_course_problem', 'User can view the problem if enrolled')]},
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
