# Generated by Django 3.2.19 on 2023-07-31 09:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import funix.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funix', '0010_auto_20230731_0433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='funix.course'),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 9, 41, 37, 338740)),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='funix.coursecomment'),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='courserating',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='funix.course'),
        ),
        migrations.AddField(
            model_name='courserating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 31, 9, 41, 37, 338366)),
        ),
        migrations.AddField(
            model_name='courserating',
            name='rating',
            field=models.IntegerField(default=1, validators=[funix.models.validate_rating]),
        ),
        migrations.AddField(
            model_name='courserating',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courserating',
            unique_together={('course', 'user')},
        ),
    ]
