# Generated by Django 3.2.19 on 2023-07-31 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import funix.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funix', '0011_auto_20230731_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='funix.course'),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='funix.course'),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='rating',
            field=models.IntegerField(validators=[funix.models.validate_rating]),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
